name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build application
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        env:
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          registry: ghcr.io
          username: $GITHUB_USER
          password: $GITHUB_TOKEN

      - name: Docker build and push into repository
        uses: docker/build-push-action@v2
        env:
          REGISTRY: gchr.io
          OWNER: ${{ github.repository_owner }}
          IMAGE_NAME: ${{ github.repository }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            $REGISTRY/$OWNER/$IMAGE_NAME:dev