name: Deploy Application

on:
  push:
    branches:
      - master

env:
  CR_URL: ${{ secrets.REGISTRY_URL }}/${{ github.repository }}

jobs:
  build:
    name: Build application
    runs-on: ubuntu-22.04
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        env:
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_PERSONAL_TOKEN }}

      - name: Docker build and push into repository
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            user=${{ secrets.GH_USER }}
            token=${{ secrets.GH_PERSONAL_TOKEN }}
          push: true
          tags: |
            ${{ env.CR_URL }}:${{ github.sha }}

  deploy:
      name: Deploy application
      runs-on: ubuntu-22.04
      needs:
        - build
      steps:
        # - name: Deploy to k8s Cluster
        #   uses: yokawasa/action-setup-kube-tools@v0.9.2
        - name: Deploy with Helm Chart
          uses: wahyd4/kubectl-helm-action@master
          env:
            KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
          with:
            args: |
              helm repo add cirkel ${{ secrets.PAGES_URL }}/charts
              helm upgrade --install auth cirkel/cirkel-chart -n cirkel-dev \
                --set image.repository=${{ env.CR_URL }} \
                --set image.tag=${{ github.sha }}

            