name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build application
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Git Configuration
        run: |
          echo ${{ secrets.NET_RC }} > .netrc
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        env:
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          registry: '${{ vars.REGISTRY_URL }}'
          username: $GITHUB_USER
          password: $GITHUB_TOKEN

      - name: Docker build and push into repository
        uses: docker/build-push-action@v2
        env:
          IMAGE_NAME: ${{ github.repository }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            $REGISTRY/cirkel-mc/$IMAGE_NAME:${{ github.sha }}

  deploy:
      name: Deploy application
      runs-on: ubuntu-22.04
      needs:
        - build
      steps:
        - name: Deploy with Helm Chart
          uses: vimeda/helm@v1.7.0
          with:
            release: ${{ github.repository }}
            namespace: cirkel-dev
            repo: ${{ vars.PAGES_URL }}/charts
            repo-alias: cirkel
            chart: 'cirkel/cirkel-chart'
            token: ${{ secrets.GITHUB_TOKEN }}
            version: ${{ github.sha }}
            values: |
              image:
                repository: ${{ vars.REGISTRY_URL }}/${{ github.repository }}
                tag: ${{ github.sha }}

            